name: "Feature Request"
description: Submit a suggestion to help us improve the Line Bot.
title: "[Feat]: "
labels: ["feat", "enhancement"]
# assignees:
#   - line-dine-mapper-team
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit this feature request! Your feedback is valuable in helping us improve the Line Bot.
  - type: textarea
    id: feature_description
    attributes:
      label: "Describe the Feature"
      description: "A clear and concise description of what you want to happen. If applicable, add mockups or diagrams to help illustrate your idea."
    validations:
      required: true
  - type: textarea
    id: benefit
    attributes:
      label: "Benefits"
      description: "Explain the benefits this feature would provide."
      value: |
        1. Improve usability...
        2. Increase efficiency...
        3. Enhance user experience...
    validations:
      required: true
  - type: input
    id: context
    attributes:
      label: "Context"
      description: "Any additional context or information about the environment where the feature would be useful?"
      placeholder: "e.g., In scenarios where multiple users..."
    validations:
      required: true
  - type: checkboxes
    id: agreements
    attributes:
      label: "Confirmations"
      description: "Before submitting the request, please confirm the following:"
      options:
        - label: "I have followed the [Code of Conduct](https://github.com/line-dine-mapper/.github/blob/main/CODE_OF_CONDUCT.md)"
          required: true
        - label: "I have checked that there isn't [already a similar feature request](https://github.com/line-dine-mapper/issues) to avoid creating a duplicate."
          required: true
